version: '3.4'
services:
  php:
    image: ghcr.io/kilip/yawik-php-dev
    volumes:
      - ./api:/srv/api:rw,cached
      - ./docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      MONGODB_URL: mongodb://yawik:yawik@database:27017
      MONGODB_DB: yawik

  pwa:
    image: ghcr.io/kilip/yawik-pwa-dev
    build:
      target: "yawik_pwa_dev"
    volumes:
      - "./pwa:/usr/src/pwa:rw,cached"

  caddy:
    image: ghcr.io/kilip/yawik-caddy-dev
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo /srv/mercure-assets/

  database:
    volumes:
      - ./var/mongo/data:/data/db:rw
      - ./docker/mongo:/dump:rw
