version: '3.4'
services:
  php:
    image: ghcr.io/kilip/yawik-php-dev
    #volumes:
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      MONGODB_URL: mongodb://yawik:yawik@database:27017
      MONGODB_DB: yawik

  pwa:
    image: ghcr.io/kilip/yawik-pwa-dev
    build:
      target: "yawik_pwa_dev"

  caddy:
    image: ghcr.io/kilip/yawik-caddy-dev
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo /srv/mercure-assets/
