doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: '%env(resolve:MONGODB_DB)%'
  #fixture_loader: Yawik\Module\Resource\Fixtures\FixtureLoader
