parameters:
  yawik.resource.fixtures_dir: "%kernel.project_dir%/fixtures"

# Default config
fidry_alice_data_fixtures:
  default_purge_mode: truncate # default is "delete" but you can change it to "truncate" or "no_purge"
  db_drivers:
    doctrine_mongodb_odm: ~
