doctrine_mongodb:
  document_managers:
    default:
      mappings:
        job:
          is_bundle: false
          type: xml
          dir: '%yawik.job.base_path%/Resources/doctrine'
          prefix: 'Yawik\Job\Model'
  resolve_target_documents:
    Yawik\Job\Model\JobInterface: Yawik\Job\Model\Job

api_platform:
  mapping:
    paths: ['%yawik.job.base_path%/Resources/api']

framework:
  serializer:
    mapping:
      paths: ['%yawik.job.base_path%/Resources/serialization']
