stages:
  - build
  - test
  - deploy
services:
  - docker:dind

image: tmaier/docker-compose:latest

build:
  stage: build
  script:
    - docker-compose pull --ignore-pull-failures || true
    - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
    - |
      while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
        case $status in
          starting) sleep 1;;
            healthy) return;;
            unhealthy)
              docker-compose ps
              docker-compose logs
            return
            ;;
          esac
        done
      return
    - curl -v -o /dev/null http://localhost
    - curl  -vk -o /dev/null https://localhost
    - docker image ls
    - docker-compose exec -T php ./vendor/bin/phpunit
