image: docker:stable
stages:
    - test
    - build
    - deploy

services:
    - docker:dind

build:
    stage: build
    script:
        - docker login -u gitlab-deploy-token -p $CI_DEPLOY_TOKEN $CI_REGISTRY
        - ./tool build
