stages:
    - test
    - build
    - deploy
        
build:
    stage: build
    image: docker:stable
    service:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_DEPLOY_TOKEN $CI_REGISTRY
        - ./tool build
