stages:
    - test
    - build
    - deploy
services:
    - docker:dind

image: tmaier/docker-compose:latest

build:
    stage: build
    script:
        - docker login -u gitlab-deploy-token -p $CI_DEPLOY_TOKEN $CI_REGISTRY
        - docker-compose pull
