doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options:
        username: "yawik"
        password: "yawik"
        authSource: "admin"
mongo_db_migrations:
  collection_name: "migration_versions"
  database_name: "%env(resolve:MONGODB_DB)%"
  dir_name: "%kernel.project_dir%/src/Migration"
  script_dir_name: "%kernel.project_dir%/scripts"
  name: "Yawik MongoDB Migrations"
  namespace: "Yawik\\Migration"
