doctrine_mongodb:
  document_managers:
    default:
      mappings:
        organization:
          is_bundle: false
          type: xml
          prefix: 'Yawik\Organization\Model'
          dir: '%yawik.organization.base_path%/Resources/doctrine'

api_platform:
  mapping:
    paths: ['%yawik.job.base_path%/Resources/api']

framework:
  serializer:
    mapping:
      paths: ['%yawik.job.base_path%/Resources/serializer']
