parameters:
  doctrine_mongodb.odm.connection.class: Yawik\Resource\Doctrine\Client
doctrine_mongodb:
  types:
    tz_date: Yawik\Resource\Doctrine\TimezoneAwareDate

stof_doctrine_extensions:
  mongodb:
    default:
      timestampable: true
