parameters:
  yawik.api_prefix: '%env(resolve:API_PLATFORM_PREFIX)%'
doctrine_mongodb:
  document_managers:
    default:
      mappings:
        resource:
          is_bundle: false
          type: xml
          dir: '%yawik.resource.base_path%/Resources/doctrine'
          prefix: 'Yawik\Resource\Model'
        resource_annotation:
          is_bundle: false
          type: annotation
          dir: '%yawik.resource.base_path%/File'
          prefix: 'Yawik\Resource\File'
  resolve_target_documents:
    Yawik\Resource\File\FileMetadataInterface: Yawik\Resource\File\FileMetadata

api_platform:
  defaults:
    pagination_items_per_page: 10
  mapping:
    paths:
      - '%yawik.resource.base_path%/Resources/api'
      - '%yawik.resource.base_path%/File'

framework:
  serializer:
    mapping:
      paths: ['%yawik.resource.base_path%/Resources/serialization']
